### ISSUE TITLE
Difference in volumes generated from the user interface and those generated by the API.

### ISSUE THREAD

**Issue by dianamariand92** [EOSC-synergy/sqaaas-api-server#112]
@orviz Volumes that are created through the web interface are not displayed in the docker-compose.yaml file generated by the API. The screenshots show the data sent by the web (including the volumes) and the response from the API.

Note: Example repository: https://github.com/EOSC-synergy/saps-scheduler

![image](https://user-images.githubusercontent.com/36927150/132850973-48792560-ad85-4016-b011-20da6cb0a9a3.png)
![image](https://user-images.githubusercontent.com/36927150/132850989-0d1f1a9c-c0f1-4323-860a-39a43a6d8bcb.png)

**Comment by orviz** [comment]
Solved in 87484048be3b0ad9e102b9f06b65ca906551a6b4
