### ISSUE TITLE
Missing spaces in scripts

### ISSUE THREAD

**Issue by dianamariand92** [EOSC-synergy/sqaaas-api-server#113]
@orviz There are missing spaces in the script that is generated to run the commands.

![image](https://user-images.githubusercontent.com/36927150/132851315-1ab6a428-8f53-4540-b42b-9166b500bb2f.png)

**Comment by alvarolopez** [comment]
@dianamariand92 this is a harmless, cosmetic fix. The command should be able to run anyway.
